### PR TITLE
add formatting, git and nb-diff extensions

### PR DESCRIPTION
**Pull request by enryH**
Hey,

I would like to propose some additional extension to the default juptyer lab installation on erda:)

- [git](https://github.com/jupyterlab/jupyterlab-git) (for easier handling of repositories)
- [nb-dime](https://nbdime.readthedocs.io/en/latest/extensions.html) (for diff views of notebooks)
- [code-formatter](https://jupyterlab-code-formatter.readthedocs.io/en/latest/index.html) (for automatic formatting of notebooks)

I build the resulting image locally and tested it briefly. I guess you normally add further tests?!

Best, 
Henry

### CODE REVIEW

**Comment by rasmunk** [comment]
Hi Henry,

Thank you for proposing these improvements.

1) I guess you normally add further tests?
yes, when adding additional modules are added to any of the Notebooks, it is customary to add tests, in the form of a test Notebook in the specified Notebook image directory (tests/notebooks/) that verify that the addition is working correctly. If you could please add tests for the three additions, I would subsequently merge it when they are passing successfully.

Also, git is already included as part of the base installation, as per:

https://github.com/ucphhpc/nbi-jupyter-docker-stacks/blob/7c6a79d1a56898768b5fadc1543077375c428b18/base-notebook/Dockerfile#L23

Have you had trouble with using it in any particular Notebook image?

**Comment by enryH** [comment]
git is working fine as a command line tool. It would be just easier to use it from within jupterlab using `jupyterlab-git` (I could rename the link). I can add some screenshoots tomorrow as motivation for the extension.

Looking at your [test notebook](https://nbviewer.jupyter.org/github/ucphhpc/nbi-jupyter-docker-stacks/blob/master/base-notebook/tests/notebooks/base_notebook.ipynb), I do not know how to test extension. Is there an example for testing  jupyterlab extension?
Thanks for the help so far:)

**Comment by enryH** [comment]
One screen shot showing the jupyterlab git and the nbdime package extension in use:

image

**Comment by rasmunk** [comment]
No worries :)

Ahh I see, for sure that is a nice addition to JupyterLab.
Since it is not a particular modul for a Jupyter environment, nor a command line binary, we currently don't have a standardised way of testing the JupyterLab extensions, beyond them being successfully installed :)

Regards
Rasmus

**Pull request merged**
